### ISSUE TITLE
https with Kubernetes ingress not working

### ISSUE THREAD

**Issue by Acromonkey** [webanno/webanno#1649]
Hello!

I want to run WebAnno in a Kubernetes cluster, using a deployment (with the WebAnno Docker image), a service pointing to that WebAnno Pod and an ingress to access to it from outside the cluster. In ingress my setting is 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-webanno
  annotations:
    ingress.bluemix.net/client-max-body-size: size=400m
    ingress.bluemix.net/redirect-to-https: "True"
spec:
  rules:
  - host: webanno.<MYDOMAIN>
    http:
      paths:
      - backend:
          serviceName: service-webanno
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - webanno.<MYDOMAIN>
    secretName: <MYSECRET>
```
Ingress, service, deployment and the pod are running well in the cluster, and if when I want to access webanno in my browser from remote, also get the login screen from WebAnno (on the redirected URL starting with https://)

But when I then enter admin/admin, the next thing I see is 

> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Wed Mar 25 11:07:16 UTC 2020
> There was an unexpected error (type=Bad Request, status=400).
> Origin does not correspond to request

The log in the pod does not show any activity appart from having created a user/password tuple admin:admin.

If I run the exactly same setting, but the ingress pod without the line 
`ingress.bluemix.net/redirect-to-https: "True"`
everthing works perfectly.

So, it seems that it cannot deal with https. 

Does anybody have an idea how to deal with that? Is it a bug or did I just oversee something?
